"""change id to char in quarto

Revision ID: 24191cbe374c
Revises: b497da662b72
Create Date: 2025-10-27 20:24:24.941258
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24191cbe374c'
down_revision: Union[str, Sequence[str], None] = 'b497da662b72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted manually ###
    op.create_table(
        'TB_QUARTO',
        sa.Column('id', sa.CHAR(length=36), nullable=False),
        sa.Column('numero', sa.Integer(), nullable=False),
        sa.Column('tipo', sa.Enum('STANDARD', 'DELUXE', 'SUITE', name='tipoquartoenum'), nullable=False),
        sa.Column('capacidade', sa.Integer(), nullable=False),
        sa.Column('valor_diaria', sa.Float(), nullable=False),
        sa.Column('status', sa.Enum('ATIVO', 'INATIVO', name='statusquartoenum'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('numero')
    )

    op.create_table(
        'TB_RESERVA',
        sa.Column('id', sa.CHAR(length=36), nullable=False),
        sa.Column('quarto_id', sa.CHAR(length=36), nullable=False),
        sa.Column('nome_hospede', sa.String(length=100), nullable=False),
        sa.Column('data_checkin_previsto', sa.Date(), nullable=False),
        sa.Column('data_checkout_previsto', sa.Date(), nullable=False),
        sa.Column('status', sa.Enum('CREATED', 'CHECKED_IN', 'CHECKED_OUT', 'CANCELED', name='statusreservaenum'), nullable=False),
        sa.Column('valor_total', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(['quarto_id'], ['TB_QUARTO.id']),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TB_RESERVA')
    op.drop_table('TB_QUARTO')
    # ### end Alembic commands ###
