"""create table quarto

Revision ID: b497da662b72
Revises: 
Create Date: 2025-10-27 19:53:21.740462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b497da662b72'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TB_QUARTO',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('STANDARD', 'DELUXE', 'SUITE', name='tipoquartoenum'), nullable=False),
    sa.Column('capacidade', sa.Integer(), nullable=False),
    sa.Column('valor_diaria', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('ATIVO', 'INATIVO', name='statusquartoenum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('TB_RESERVA',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quarto_id', sa.Integer(), nullable=False),
    sa.Column('nome_hospede', sa.String(length=100), nullable=False),
    sa.Column('data_checkin_previsto', sa.Date(), nullable=False),
    sa.Column('data_checkout_previsto', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'CHECKED_IN', 'CHECKED_OUT', 'CANCELED', name='statusreservaenum'), nullable=False),
    sa.Column('valor_total', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['quarto_id'], ['TB_QUARTO.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TB_RESERVA')
    op.drop_table('TB_QUARTO')
    # ### end Alembic commands ###
